parameters: {}
environment:
  DB_NAME: test
  DB_USERNAME: tester
  DB_PASSWORD: password
  DB_HOST: localhost
middleware:
  - path: middleware/auth.mjs
    type: authorization
packages:
    - name: test
      path: packages
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello
          environment: {}
        - name: health
          environment: {}
        - name: binary
          environment: {}
